### PR TITLE
Add CodeClimate test coverage reporting

### PR DESCRIPTION
**Pull request by prestonvanloon**
Current coverage is: 63% !

Check out: https://codeclimate.com/github/nycJSorg/angular-presentation

We can add a badge to the README later.

### CODE REVIEW

**Comment by kirjs** [comment]
That's like 62% more than I expected

**Comment by prestonvanloon** [comment]
OK this is good to go. Ignore the last test failure. I think i was hammering codeclimate too quickly. Travis passes. PTAL


Also, I think that 63% is test coverage. Not code coverage (which would likely be extremely low due to monaco existing, among other things.)

**Comment by tessaSAC** [comment]
Added the badge #505 looks like the pr might have confused code climate though

**Comment by prestonvanloon** [comment]
Monaco (and others in `src/assets`) made Code Climate very flakey. I added a config file to exclude those directories. This should be good to go now.

`src/assets` had 7800 issues. After this, we'll have less than 200 real issues.

**Comment by prestonvanloon** [comment]
Please squash this PR into a single commit. I had a lot of trial and error to get this to work properly.

**Pull request merged**
